### ISSUE TITLE
LD_LIBRARY_PATH = <ROOT>/install/install?

### ISSUE THREAD

**Issue by cbdwtv** [AllegorithmicSAS/gpu-free-gl#2]
Looking at the docs it says to export LD_LIBRARY_PATH to <ROOT>/install/install
but after building I do not have that folder.
Was this a typo in adding the install directory twice? or am I missing a step in my build process.
Just want to make sure I did not miss anything.
TIA

**Comment by colaub** [comment]
Hi, 
This project needs a lot of dependencies and compilations which could be cumbersome.
We did a docker project to make this project easier, I suggest you try it: 
https://github.com/AllegorithmicSAS/sat_batchtools_gpu_free
Follow steps from readme.md and don't hesitate to ask questions if needed.

**Comment by cbdwtv** [comment]
haha I guess I should have asked this question before I did all that cumbersome work.
thank you so much for the docker project! will reach out if needed
